#!/bin/bash

/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 1 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 2 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 3 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 4 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 5 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 6 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 10 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m3s10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 1 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 2 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 3 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 4 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 5 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 6 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 10 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z200m2s10.tab



/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 1 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 2 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 3 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 4 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 5 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 6 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 3 -s 10 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m3s10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 1 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 2 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 3 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 4 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 5 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 6 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 200000 -T -w -m 2 -s 10 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz200m2s10.tab



/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 1 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 2 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 3 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 4 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 5 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 6 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 10 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m3s10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 1 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 2 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 3 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 4 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 5 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 6 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 10 > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500m2s10.tab


/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 1 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 2 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 3 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 4 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 5 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 6 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 3 -s 10 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m3s10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 1 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s1.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 2 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s2.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 3 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s3.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 4 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s4.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 5 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s5.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 6 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s6.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w -m 2 -s 10 -R > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.Rz500m2s10.tab





