#!/bin/bash

/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 10000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 30000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z30.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 50000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z50.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 75000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z75.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 100000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z100.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 300000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z300.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 500000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z500.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 750000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z750.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 1000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z1000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 3000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z3000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/thunnus/fThuAlb1_vs_fThuMac1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_914725855.1_fThuAlb1.1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/thunnus/GCF_910596095.1_fThuMac1.1_genomic.x.gff --genbank-gff -z 5000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/fThuAlb1_vs_fThuMac1.microsynteny.z5000.tab



/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 10000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 30000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z30.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 50000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z50.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 75000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z75.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 100000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z100.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 300000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z300.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 500000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z500.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 750000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z750.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 1000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z1000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 3000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z3000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 5000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z5000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/bufo/Bgarg_vs_aBufBuf1.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/bufo/GCF_014858855.1_ASM1485885v1_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/bufo/GCF_905171765.1_aBufBuf1.1_genomic.x.gff --genbank-gff -z 10000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Bgarg_vs_aBufBuf1.microsynteny.z10000.tab



/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 10000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z10.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 30000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z30.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 50000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z50.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 75000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z75.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 100000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z100.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 300000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z300.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 500000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z500.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 750000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z750.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 1000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z1000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 3000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z3000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 5000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z5000.tab
/home/wrf/git/genomeGTFtools/microsynteny.py -b /mnt/data/project/speciation-synteny/datasets/octopus/Obi_vs_Osi.blastp.tab -q /mnt/data/project/speciation-synteny/datasets/octopus/GCF_001194135.2_ASM119413v2_genomic.x.gff -d /mnt/data/project/speciation-synteny/datasets/octopus/GCF_006345805.1_ASM634580v1_genomic.x.gff --genbank-gff -z 10000000 -T -w > /mnt/data/project/speciation-synteny/datasets/microsynteny_calibration/Obi_vs_Osi.microsynteny.z10000.tab






